swagger: '2.0'
host: itraining.zhanzy.xyz
basePath: /api/v1
info:
  description: |
    这是我们的API设计文档
  version: 1.0.0
  title: iTraining
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: iTraining训练打卡小程序
  url: 'https://github.com/iTraining/document'
tags:
  - name: v1
    description: API v1
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /sessionid:
    x-summary: Session Id
    get:
      tags:
        - v1
      summary: Get session_id
      parameters:
        - name: code
          in: query
          type: string
          required: true
          description: 小程序通过wx.login()获取的用户授权码
      responses:
        200:
          description: Get session_id successfully
          schema:
            $ref: '#/definitions/SessionId'
          examples:
            application/json:
              session_id: 'FDBDA3fb1D'
definitions:
  SessionId:
    title: Session id
    type: object
    properties:
      session_id:
        type: string
    required:
      - session_id
    example:
      session_id: 'FDBDA3fb1D'